# Generated by Django 2.1.5 on 2019-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcription',
            name='stripe_subscription_id',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
